### ISSUE TITLE
Salt and Sacrifice 

### ISSUE THREAD

**Issue by Sobarashi** [LinkOFF7/SaltTextTool#1]
Hello sir

It works in the loot.zls file only and does not work on other file like dialog.zdx

<img width="674" alt="2022-09-03 01_14_33-C__Windows_System32_cmd exe" src="https://user-images.githubusercontent.com/62736436/188241957-aab94245-f0f2-4eaf-ae11-f4bc2297ffb0.png">

**Comment by LinkOFF7** [comment]
Use the appropriate mode to extract dialog.zdx:
salt_strings.exe -mode dialog -extract json dialog.zdx

You can see the modes in README.md
